version: '3.8'
services:
  db:
    container_name: wb_analyzer_db
    image: postgres:15.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-wb_analyzer}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    container_name: wb_analyzer_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - ENV_FILE=.env
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  postgres_data_vol: