services:
  db:
    container_name: wb_analyzer_db
    image: postgres:15.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-wb_analyzer}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  app:
    container_name: wb_analyzer_app
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    depends_on:
      - db
    environment:
      - ENV_FILE=.env
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: bash -c "poetry run uvicorn apps.api.v1.main:app --host 0.0.0.0 --port 8000 --reload"
volumes:
  postgres_data: